export const state = {
    scene: null,
    renderer: null,
    camera: null,
    followCamera: null,
    controls: null,
    world: null,
    dominoBodies: [],
    dominoMeshes: [],
    ball: null,
    seesaw: null,
    animationStarted: false,
    currentCamera: null,
    followTargets: [],
    followIndex: 0,
    cameraYAngle: 0,
    baseCameraOffset: new THREE.Vector3(0, 3, -8),
    currentCameraOffset: new THREE.Vector3(0, 3, -8).clone(),
    branchToFollow: new Set(),
    leftBranch: new Set(),
    rightBranch: new Set(),
    chosenBranch: null,
    branchLocked: false,
    isTransitioning: false,
    transitionStartPosition: new THREE.Vector3(),
    transitionTargetPosition: new THREE.Vector3(),
    transitionProgress: 0,
    lights: {},
    updaters: []
};